### PR TITLE
Add HTTP/1.1 request parsing and validation in handleConnection function

### PR DESCRIPTION
**Pull request by LLeon360**
:)

### CODE REVIEW

**Review by epsteinmark — CHANGES_REQUESTED** [review]
Try to use the latest stdlib for consistency and to be up-to-date when possible. Note concat (and possibly equals) work slightly differently, so make sure to change how you use the functions.

Right now, if the HTTP request is bigger than your buffer size, the remainder will never be read. Make sure to keep reading until you've gotten everything! Feel free to reference the TCP echo server solution, or to reach out for help if needed.

HTTP doesn't have a strong definition of what methods are valid. You may validate the method by what defines a valid token if you'd like, or define a set of methods you accept, in which case you may want to use the standard HTTP methods. Check the RFC for nuances in method checking if you choose the second approach.

For ease of legibility, consider adding newlines at the end of the body. Also make sure to include a Content-Length field in the header when sending a body!
 
Content-length is not required (and is in fact discouraged) if there's no body (i.e. a GET request). https://www.rfc-editor.org/rfc/rfc9110#section-8.6-5. Content-Type is also not strictly required. You can, however, validate for the inclusion of the HOST field in the header.

**Comment by epsteinmark** [comment]
Good first start! You're most of the way there. Feel free to reach out if you need any help.

**Comment by LLeon360** [comment]
Question: If I add newlines for legibility, I should probably change content-length which would mean that the response has a different content length but in the example on Discord, the content-length is the same. I'm currently adding CLRFs to the end of the response body and also adding to the content length. Is this correct?

**Comment by epsteinmark** [comment]
> Question: If I add newlines for legibility, I should probably change content-length which would mean that the response has a different content length but in the example on Discord, the content-length is the same. I'm currently adding CLRFs to the end of the response body and also adding to the content length. Is this correct?

If you're referring to the content and response from Jason and Andrew respectively, then the content length should be the same because the body is the same. I should have clarified that you should add the newline to your write for errors. For instance (in the old PR I haven't looked at new one) your "Invalid request, Missing Content-Length header" didn't have a \n which made my terminal cursor appear on the same line which is unconventional.

**Review by epsteinmark — COMMENTED** [review]
We'll go over this during the Lab today.

**Pull request merged**
